server:
  port: 80


spring:
  profiles:
    active: dev
  datasource:
    type: com.mchange.v2.c3p0.ComboPooledDataSource
    driverClass: com.mysql.jdbc.Driver
    jdbcUrl: jdbc:mysql://127.0.0.1:3306/readhub?useUnicode=true&characterEncoding=UTF-8
    user: root
    password: root
    maxPoolSize: 200
    minPoolSize: 5
    initialPoolSize: 5
    acquireIncrement: 5
    idleConnectionTestPeriod: 28000
    maxIdleTime: 28000

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: cn.peace.readhub.domain




